version: "3.7"
services:
   database:
     image: mariadb:10.6.7
     container_name: database
     restart: unless-stopped
     tty: true
     ports:
        - "3306:3306"
     command: --default-authentication-plugin=mysql_native_password
     volumes:
        - ./database:/docker-entrypoint-initdb.d
        #- ./database/conf-search.cnf:/etc/mysql/conf.d/my.cnf
     environment:
        MYSQL_DATABASE: "edusor"
        #MYSQL_USER: "root"
        MYSQL_PASSWORD: "demo"
        MYSQL_ROOT_PASSWORD: "123456"
        SERVICE_TAGS: dev
        SERVICE_NAME: mariadb
   # frontend:
   #    image: node:16.14-alpine
   #    container_name: frontend
   #    working_dir: /var/www
   #    volumes:
   #       - ./frontend-react/:/var/www
   #    tty: true
   #    ports:
   #       - "6658:3000"
   #    networks:
   #       - app
   #    command: sh -c "npm install && npm run dev"
networks:
   app:
