version: "3.7"
services:
  #  nginx:
  #     image: nginx:1.21.5-alpine
  #     container_name: nginx_proxy
  #     ports:
  #        - "80:80"
  #     volumes:
  #        - ./default.conf:/etc/nginx/conf.d/default.conf
  #     networks:
  #        - app
      # depends_on:
      #    - mariadb
  #  mariadb:
  #     image: mariadb:10.6.7
  #     container_name: mysql
  #     restart: unless-stopped
  #     tty: true
  #     ports:
  #        - "3306:3306"
  #     command: --default-authentication-plugin=mysql_native_password
  #     volumes:
  #        - ./database/sqldump:/docker-entrypoint-initdb.d
  #        - ./database/conf-search.cnf:/etc/mysql/conf.d/my.cnf
  #     environment:
  #        MYSQL_DATABASE: "onroad"
  #        MYSQL_USER: "demo"
  #        MYSQL_PASSWORD: "demo"
  #        MYSQL_ROOT_PASSWORD: "demo"
  #        SERVICE_TAGS: dev
  #        SERVICE_NAME: mariadb
  #     networks:
  #        app:
   backend:
      image: node:14-bullseye
      container_name: backend
      working_dir: /var/www
      volumes:
         - ./backend/:/var/www
      tty: true
      ports:
         - "8080:8075"
      networks:
         app:
      command: >
         sh -c "npm install && npm run start:dev"
   frontend:
      image: node:16.14-alpine
      container_name: frontend
      working_dir: /var/www
      volumes:
         - ./frontend-react/:/var/www
      tty: true
      ports:
         - "4059:3000"
      networks:
         - app
      depends_on:
         - backend
      command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

networks:
   app:
